config/routes.rb
Quiz::Application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { confirmations: "confirmations" }
  #devise_for :administrators

  root to: "top#index"
  match "wellcome", to: "users#wellcome"
  resource :users
  resource :account_services
  resources :answer_sheets do
    collection do
      get 'mylogs'
    end
  end

  resources :examinations do
    member do
      post 'start_examination'
      put 'complete_examination'
    end
    resources :questions
  end

  resources :questions do
    member do
      post 'answer'
    end
  end

  namespace :admin do
    #devise_for :administrators, controllers: { sessions: 'admin/sessions' }
    devise_for :administrators, :controllers => { :sessions => "admin/sessions" }
    root to: "top#index"
    resources :administrators
    resources :users
    resources :examinations do
      resources :questions
    end
    resources :questions do
      resources :question_choices
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :examination, dependent: :destroy
  has_many :question_choices, dependent: :destroy
  has_many :answer
  validates :caption, :description, :credits, presence: true
end

app/controllers/admin/questions_controller.rb
# coding: utf-8
class Admin::QuestionsController < Admin::Base
  before_filter :authenticate_admin_administrator!
  def new
    @examination = Examination.find(params[:examination_id])
    @question = Question.new
  end

  def create
    @examination = Examination.find(params[:examination_id])
    @question = Question.new
    @question.assign_attributes params[:question]
    if @question.valid?
      @examination.questions << @question
      return redirect_to [:admin, @examination, @question], notice: '保存しました'
    end
    flash[:error] = '以下の問題を確認してください'
    return render 'new'
  end

  def index
    @examination = Examination.find(params[:examination_id])
    @questions = Kaminari::paginate_array(@examination.questions.order(:id)).
                  page(params[:page]).per(5)
  end

  def show
    @question = Question.find(params[:id])
    @examination = @question.examination
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.assign_attributes params[:question]
    if @question.save
      return redirect_to [:admin, @question.examination, @question],
        notice: '更新が完了しました。'
    end
    flash[:error] = '更新に失敗しました。'
    return render 'edit'
  end
end

app/controllers/questions_controller.rb
# coding: utf-8
class QuestionsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @examination = Examination.find_by_id(params[:examination_id])
    @questions = Kaminari::paginate_array(@examination.questions).page(params[:page]).per(10)
  end

  def show
    @question = Question.find_by_id(params[:id])
  end

  def answer
    question_id = params[:id]
    @question_choice = QuestionChoice.find_by_id params[question_id]
    @question = @question_choice.question

    Answer.commit_answer(session[:answer_sheet_id], question_id, @question_choice.id)
    return redirect_to [@question.examination, :questions], notice: '保存しました'
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/index.html.erb
<h3>
  <i class="icon-pencil"></i> <%= @examination.name %> Questions
</h3>
<table class="table table-hover table-striped">
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <th><%= question.caption %></th>
        <td><%= question.description %></td>
        <td>
          <%= link_to [@examination, question], class: 'btn btn-primary' do %>
            <i class="icon-pencil"></i> 解答
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @questions %>
<%= simple_form_for [:complete_examination, @examination], html: {class: 'form-holizonal', method: :put} do |f| %>
  <%= button_tag class: 'btn btn-primary btn-large' do %>
    <i class="icon-pencil icon-white"></i> 終了する
  <% end %>
<% end %>

app/views/questions/show.html.erb
<h3><i class="icon-pencil"></i> <%= @question.caption %></h3>
<h4><%= @question.description %></h4>
<hr />
<%= form_tag answer_question_path, method: :post do %>
  <ol>
    <% @question.question_choices.each do |choice| %>
      <li>
        <p>
          <%= label @question.id, choice.id, class: 'radio' do %>
            <%= radio_button_tag @question.id, choice.id %>
            <%= choice.caption %>
          <% end %>
        </p>
      </li>
    <% end %>
  </ol>
  <%= button_tag type: :submit, class: 'btn btn-primary btn-large' do%>
    <i class="icon-ok"></i> 解答する
  <% end %>
<% end %>